### ISSUE TITLE
No more TMATE_DOMAIN

### ISSUE THREAD

**Issue by nviennot** [jjasghar/chef-tmate-slave#1]
Hi JJ,

tmate no longer have the TMATE_DOMAIN constant defined.
Now, you can pass the hostname that you want as an argument `-h host`.

So you can pass something like hostname.domain.
Example: https://github.com/nviennot/tmate-kitchen/blob/master/site-cookbooks/tmate/recipes/default.rb#L41
https://github.com/nviennot/tmate-kitchen/blob/master/site-cookbooks/tmate/templates/default/tmate.conf.erb#L13

**Comment by jjasghar** [comment]
I removed it from the cookbook.  I should really create a way to start up tmate-slave too. I might just steal from your suggestions if that's cool ;)

**Comment by jjasghar** [comment]
I removed it from the cookbook. And got the lint testing done. I'll close this for now, the "auto-start" is on my to-do list.

**Comment by nviennot** [comment]
great!

thanks :)
